In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle

# Step 1: Load the dataset
data = pd.read_csv('synthetic_data_with_stress_heatstroke_arrhythmia.csv')

# Step 2: Preprocess the data
# Handle missing values if any
data.dropna(inplace=True)

# Step 3: Split the data into features and target variables
X = data[['Temperature (°C)', 'Pulse (BPM)', 'ECG (BPM)', 'Age']]
y_stress = data['Stress Level']
y_heatstroke = data['Heatstroke']

# Step 4: Split the data into training and testing sets
X_train, X_test, y_stress_train, y_stress_test, y_heatstroke_train, y_heatstroke_test = train_test_split(
    X, y_stress, y_heatstroke, test_size=0.2, random_state=42)

# Step 5: Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 6: Model Selection and Training for Stress Prediction
svm_stress_classifier = SVC(kernel='linear', random_state=42)
svm_stress_classifier.fit(X_train_scaled, y_stress_train)

# Step 7: Model Evaluation for Stress Prediction
y_stress_pred = svm_stress_classifier.predict(X_test_scaled)
accuracy_stress = accuracy_score(y_stress_test, y_stress_pred)
print("Stress Prediction Accuracy:", accuracy_stress)
print("\nStress Classification Report:")
print(classification_report(y_stress_test, y_stress_pred))
print("\nStress Confusion Matrix:")
print(confusion_matrix(y_stress_test, y_stress_pred))

# Step 8: Model Selection and Training for Heatstroke Prediction
svm_heatstroke_classifier = SVC(kernel='linear', random_state=42)
svm_heatstroke_classifier.fit(X_train_scaled, y_heatstroke_train)

# Step 9: Model Evaluation for Heatstroke Prediction
y_heatstroke_pred = svm_heatstroke_classifier.predict(X_test_scaled)
accuracy_heatstroke = accuracy_score(y_heatstroke_test, y_heatstroke_pred)
print("\nHeatstroke Prediction Accuracy:", accuracy_heatstroke)
print("\nHeatstroke Classification Report:")
print(classification_report(y_heatstroke_test, y_heatstroke_pred))
print("\nHeatstroke Confusion Matrix:")
print(confusion_matrix(y_heatstroke_test, y_heatstroke_pred))

# Step 10: Function to Predict Stress and Heatstroke for New Patients
def predict_health_status(temperature, pulse, ecg, age):
    # Scale the input features
    new_patient_data = np.array([[temperature, pulse, ecg, age]])
    new_patient_data_scaled = scaler.transform(new_patient_data)
    
    # Predict stress level
    predicted_stress = svm_stress_classifier.predict(new_patient_data_scaled)[0]
    
    # Predict heatstroke
    predicted_heatstroke = svm_heatstroke_classifier.predict(new_patient_data_scaled)[0]
    
    return predicted_stress, predicted_heatstroke

# Example usage:
temperature_value = 30
pulse_value = 76
ecg_value = 132
age_value = 25

predicted_stress, predicted_heatstroke = predict_health_status(
    temperature_value, pulse_value, ecg_value, age_value)

print("\nPredicted Stress Level for New Patient:", predicted_stress)
print("Predicted Heatstroke for New Patient:", predicted_heatstroke)

# Your code to save the trained models and scaler

# Save the trained models to disk
with open('svm_stress_model.pkl', 'wb') as f:
    pickle.dump(svm_stress_classifier, f)

with open('svm_heatstroke_model.pkl', 'wb') as f:
    pickle.dump(svm_heatstroke_classifier, f)

# Save the trained scaler to disk
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

Stress Prediction Accuracy: 0.96

Stress Classification Report:
              precision    recall  f1-score   support

        High       0.97      1.00      0.99       185
         Low       0.70      0.88      0.78         8
    Moderate       0.00      0.00      0.00         7

    accuracy                           0.96       200
   macro avg       0.56      0.62      0.59       200
weighted avg       0.93      0.96      0.94       200


Stress Confusion Matrix:
[[185   0   0]
 [  1   7   0]
 [  4   3   0]]

Heatstroke Prediction Accuracy: 0.925

Heatstroke Classification Report:
              precision    recall  f1-score   support

          No       0.95      0.97      0.96       175
         Yes       0.73      0.64      0.68        25

    accuracy                           0.93       200
   macro avg       0.84      0.80      0.82       200
weighted avg       0.92      0.93      0.92       200


Heatstroke Confusion Matrix:
[[169   6]
 [  9  16]]

Predicted Stress Level for N

C:\Users\Prathibha\anaconda3\anaconda new\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Prathibha\anaconda3\anaconda new\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Prathibha\anaconda3\anaconda new\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\U